---
title: "Data Demographics Part 2"
author: "Ian Zhang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE)
```

```{r}
setwd('C:/Users/zjxph/Desktop/work/comp_phys/venturi/230914')
library(dplyr)
df <- read.table('classNoMissNoText.csv',
           header = TRUE,
           sep = ',',
           stringsAsFactors = FALSE)
df_dplyr <- read.table('classNoMissNoText.csv',
           header = TRUE,
           sep = ',',
           stringsAsFactors = FALSE)
```
## 1.
```{r}
df$age[4]
```

## 2.
```{r}
max(df$age)
```

## 3.
```{r}
df$shoe[14]
```

## 4.
```{r}
df$expGrade[10]
```

## 5.
selecting a row shows all variables of a observation
<br>
selecting a column shows all values of a variable
<br>
<br>
selecting row and column, respectively:
```{r}
df[2,]
df[,2]
```


## 6.
```{r}
class(df)
```

## 7.
```{r}
class(df$expGrade)
```

## 8.
```{r}
class(df$siblings)
```

## 9.
```{r}
siblings_squared <- df$siblings^2
siblings_squared
```

## 10.
## 11.
## 12.
```{r}
df$siblingsInt <- as.integer(df$siblings)
names(df)
class(df$siblingsInt)
```

## 13.
## 14.
## 15.
```{r}
class(df$age)
min(df$age)
max(df$age)
```

## 16.
```{r}
df$ageScale <- df$age / max(df$age)
df$ageScale
```

## 17.
## 18.
```{r}
df_dplyr <- df_dplyr %>%
  mutate(siblingsInt = as.integer(siblings)) %>%
  mutate(ageScale = age / max(age))
View(df_dplyr)
```







